### ISSUE TITLE
处理失败:远程主机强迫关闭了一个现有的连接。

### ISSUE THREAD

**Issue by leizt** [NiuXiangQian/chatgpt-stream#12]
处理失败:远程主机强迫关闭了一个现有的连接，怎么设置连接时长？

**Comment by NiuXiangQian** [comment]
> 处理失败:远程主机强迫关闭了一个现有的连接，怎么设置连接时长？

通过vpn连接了吗

**Comment by NiuXiangQian** [comment]
如果用了nginx 可以在nginx那里设置一下超时

**Comment by yudan0777** [comment]
@NiuXiangQian 大佬你好，我也遇到了类似的问题，希望可以帮忙看一下。
每次数据返回完成大约4分钟左右就会报这个错。

2023-12-15 16:46:26.841 [TID: N/A] [reactor-http-nio-4] WARN  c.j.j.service.OpenAIService -OpenAI返回数据关闭
2023-12-15 16:46:26.842 [TID: N/A] [reactor-http-nio-4] INFO  c.j.j.service.OpenAIService -OpenAI返回数据完成
2023-12-15 16:50:32.296 [TID: N/A] [reactor-http-nio-4] ERROR r.n.r.PooledConnectionProvider -Pooled connection observed an error
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:748)

**Comment by NiuXiangQian** [comment]
返回结果到一半就报错了吗

**Comment by yudan0777** [comment]
> 返回结果到一半就报错了吗

结果可以完整返回。但是完整返回后4分钟会报这个错。
我已经发现是我自己VPN的问题了，感谢你之前的回复。
